apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
  labels:
    app: monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      containers:
      serviceAccountName: <K8S SERVICE ACCOUNT>
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      - name: monolith
        image: gcr.io/<PROJECT ID>/monolith:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
